# --- !Ups

CREATE TABLE Organization (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	org_id VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	salt VARCHAR(255) NOT NULL
);

# --- !Downs

DROP TABLE IF EXISTS Organization;
